# Generated by Django 5.1.1 on 2024-09-20 09:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date_room', models.DateField()),
                ('account_date_pos', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('remarque', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AutreRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Banquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images/baquets/')),
            ],
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('nbchamax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('paxmax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('postnom', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=12)),
                ('nationalite', models.CharField(max_length=5)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('adresse_serv', models.CharField(max_length=30)),
                ('adresse_rdc', models.CharField(max_length=30)),
                ('lieu_nais', models.CharField(max_length=30)),
                ('date_nais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=30)),
                ('salbase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('activite', models.CharField(max_length=30)),
                ('notre_relation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='Dinner', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=40)),
                ('typen', models.CharField(max_length=15)),
                ('daten', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('p_caisse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=15)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('affectation', models.CharField(choices=[('REC', 'Réception'), ('PDV', 'Point de Vente'), ('FIN', 'Finance et Comptabilité'), ('MAG', 'Magasin et Stock'), ('HKP', 'House Keeping'), ('GAR', 'Garde et Sécurité'), ('RHM', 'Ressources Humaines'), ('INF', 'Informatique'), ('CUI', 'Cuisine'), ('GER', 'Gérance')], max_length=30)),
                ('role', models.CharField(choices=[('SUP', 'Superviseur'), ('VIC', 'Vice-Superviseur'), ('ORD', 'Ordinaire'), ('INV', 'Invité')], max_length=30)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=30)),
                ('nationalite', models.CharField(choices=[('Congolaise', 'Congolaise'), ('Rwandaise', 'Rwandaise'), ('Burundaise', 'Burundaise'), ('Kenyane', 'Kenyane'), ('Ugandaise', 'Ugandaise'), ('Zambienne', 'Zambienne'), ('Angolaise', 'Angolaise'), ('Autre', 'Autre')], max_length=30, null=True)),
                ('tel', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AutreDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=30)),
                ('libelle', models.CharField(max_length=30)),
                ('montant', models.FloatField()),
                ('dated', models.DateTimeField(auto_now=True)),
                ('autorisation1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.autorisation')),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('banquet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riviapp.banquet')),
                ('prixmensuel', models.FloatField()),
            ],
            bases=('riviapp.banquet',),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('banquet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='riviapp.banquet')),
                ('capacite', models.IntegerField()),
                ('prixoccup', models.FloatField()),
            ],
            bases=('riviapp.banquet',),
        ),
        migrations.AddField(
            model_name='banquet',
            name='bloc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.bloc'),
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6)),
                ('statut', models.CharField(max_length=20)),
                ('etage', models.CharField(max_length=20)),
                ('bloc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.bloc')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datev', models.DateField(auto_now=True)),
                ('etat', models.CharField(max_length=20)),
                ('typev', models.CharField(max_length=20)),
                ('total', models.IntegerField()),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
                ('pointvente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.pointvente')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(auto_now=True)),
                ('commentaire', models.CharField(max_length=30)),
                ('total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='DetteEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('motif', models.CharField(max_length=50)),
                ('dated', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employe')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(auto_now=True)),
                ('typec', models.CharField(max_length=30)),
                ('etat', models.CharField(max_length=15)),
                ('total', models.FloatField()),
                ('remarque', models.CharField(max_length=50)),
                ('autorisation1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.autorisation')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employe')),
            ],
        ),
        migrations.AddField(
            model_name='autorisation',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employe'),
        ),
        migrations.CreateModel(
            name='Enregistrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('datearr', models.DateTimeField()),
                ('datesor', models.DateTimeField()),
                ('provenance', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('prixnuitee', models.FloatField()),
                ('avance', models.FloatField()),
                ('nbpax', models.IntegerField()),
                ('nbjrs', models.IntegerField(default=1)),
                ('still_in', models.BooleanField(default=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('postnom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('adresse_serv', models.CharField(max_length=30)),
                ('type_ese', models.CharField(max_length=30)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.DateTimeField(auto_now=True)),
                ('typea', models.CharField(max_length=30)),
                ('etat', models.CharField(max_length=15)),
                ('total', models.FloatField()),
                ('remarque', models.CharField(max_length=50)),
                ('autorisation1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.autorisation')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('datemodif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('qte', models.FloatField()),
                ('prixu', models.FloatField()),
                ('last_pachat', models.FloatField()),
                ('datemodif', models.DateTimeField(auto_now=True)),
                ('unitmsr', models.CharField(max_length=5)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.groupe_article')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/chambres/')),
                ('description', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('prix', models.FloatField()),
                ('model', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.article')),
                ('commandeachat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.commandeachat')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.article')),
                ('commandestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.commandestock')),
            ],
        ),
        migrations.CreateModel(
            name='LocationBtq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('duree', models.IntegerField()),
                ('prixunit', models.FloatField()),
                ('totverse', models.FloatField()),
                ('reste', models.FloatField()),
                ('commentaire', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.boutique')),
            ],
        ),
        migrations.CreateModel(
            name='MenuRestau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typem', models.CharField(max_length=20)),
                ('prix', models.IntegerField()),
                ('designation', models.CharField(max_length=40)),
                ('commentaire', models.CharField(max_length=200)),
                ('datecreation', models.DateField(auto_now=True)),
                ('datefin', models.DateField()),
                ('urlimage', models.ImageField(default='', upload_to='images/menurestaurant/')),
                ('groupe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riviapp.groupemenu')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommandeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.FloatField()),
                ('compliment', models.CharField(max_length=30)),
                ('commandevente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.commandevente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.menurestau')),
            ],
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('mouvement', models.FloatField()),
                ('libelle', models.CharField(max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.operateur')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('montant', models.FloatField()),
                ('mode', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=30, null=True)),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.enregistrer')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.commandevente')),
            ],
        ),
        migrations.CreateModel(
            name='Piece_indentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=30)),
                ('date_livre', models.DateField()),
                ('date_expire', models.DateField()),
                ('lieu_livre', models.CharField(max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Remuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dater', models.DateTimeField(auto_now=True)),
                ('saljr', models.FloatField()),
                ('joursprestes', models.IntegerField()),
                ('salbrut', models.FloatField()),
                ('ipr', models.FloatField()),
                ('cnss', models.FloatField()),
                ('onem', models.FloatField()),
                ('inpp', models.FloatField()),
                ('avancesursal', models.FloatField()),
                ('netapayer', models.FloatField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.periode')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=10)),
                ('prixvalide', models.FloatField()),
                ('datearrivee', models.DateField()),
                ('datesortie', models.DateField()),
                ('nbadultes', models.IntegerField()),
                ('nbenfants', models.IntegerField()),
                ('nbchambre', models.IntegerField()),
                ('autresinfos', models.TextField()),
                ('etat_rsv', models.CharField(max_length=10)),
                ('raison_annul', models.CharField(default='', max_length=30)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.categorie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('montant', models.FloatField()),
                ('mode', models.CharField(max_length=10)),
                ('libelle', models.CharField(default='', max_length=20)),
                ('reste', models.FloatField()),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.enregistrer')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('duree', models.IntegerField()),
                ('prixunit', models.FloatField()),
                ('totverse', models.FloatField()),
                ('reste', models.FloatField()),
                ('etatrsv', models.CharField(max_length=10)),
                ('commentaire', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.client')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.departement')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.service'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('datemodif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupe_article',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.stock'),
        ),
        migrations.CreateModel(
            name='TarifAutreRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('prix', models.FloatField()),
                ('autrerevenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.autrerevenu')),
            ],
        ),
        migrations.CreateModel(
            name='LigneConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre', models.IntegerField()),
                ('consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.consommation')),
                ('tarifautrerevenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.tarifautrerevenu')),
            ],
        ),
        migrations.CreateModel(
            name='VersementBq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('montant', models.FloatField()),
                ('libelle', models.CharField(max_length=50)),
                ('locationbq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.locationbtq')),
            ],
        ),
        migrations.CreateModel(
            name='VersementSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('montant', models.FloatField()),
                ('libelle', models.CharField(max_length=50)),
                ('facilitateur', models.CharField(max_length=50)),
                ('reservationsalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.reservationsalle')),
            ],
        ),
    ]
