# Generated by Django 5.1.1 on 2024-09-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeachat',
            name='date_stockage',
            field=models.DateTimeField(null=True),
        ),
    ]
