# Generated by Django 5.1.1 on 2024-09-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0002_commandeachat_date_stockage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandestock',
            name='employe',
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandestock',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
