# Generated by Django 5.1.1 on 2024-09-20 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0003_remove_commandestock_employe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorisation',
            name='employe',
        ),
        migrations.AddField(
            model_name='autorisation',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
