# Generated by Django 5.1.1 on 2024-09-24 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0004_remove_autorisation_employe_autorisation_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandestock',
            name='typec',
        ),
        migrations.AlterField(
            model_name='commandestock',
            name='autorisation1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.autorisation'),
        ),
        migrations.AlterField(
            model_name='commandestock',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
