# Generated by Django 5.1.1 on 2024-09-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0006_commandestock_date_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.operateur'),
        ),
    ]
