# Generated by Django 5.1.1 on 2024-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0007_alter_paiement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='extra',
            field=models.BooleanField(default=False),
        ),
    ]
