# Generated by Django 5.1.1 on 2024-09-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0008_paiement_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrer',
            name='datejr',
            field=models.DateTimeField(),
        ),
    ]
