# Generated by Django 5.1.1 on 2024-09-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0009_alter_enregistrer_datejr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrer',
            name='datejr',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('datesor', models.DateTimeField()),
                ('nuitees', models.IntegerField()),
                ('montant_extra', models.FloatField()),
                ('montant_accom', models.FloatField()),
                ('credit', models.BooleanField()),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.enregistrer')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dette_transfert_chambre', to='riviapp.enregistrer')),
                ('entreprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.entreprise')),
            ],
        ),
    ]
