# Generated by Django 5.1.1 on 2024-09-26 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0010_alter_enregistrer_datejr_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut_chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datejr', models.DateTimeField(auto_now=True)),
                ('reservee', models.BooleanField(default=False)),
                ('bloquee', models.BooleanField(default=False)),
                ('hors_service', models.BooleanField(default=False)),
                ('echeance', models.DateField()),
                ('raison', models.TextField(max_length=30)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.chambre')),
            ],
        ),
    ]
