# Generated by Django 5.1.1 on 2024-09-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0011_statut_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=5)),
                ('salbase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=20)),
                ('postnom', models.TextField(max_length=20)),
                ('sexe', models.TextField(max_length=2)),
                ('etat_civil', models.TextField(max_length=5)),
                ('nb_enfant', models.IntegerField()),
                ('date_naiss', models.DateField()),
                ('date_engage', models.DateField()),
                ('adresse', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=30)),
                ('niveau_etu', models.CharField(max_length=30)),
                ('fonction', models.CharField(max_length=30)),
                ('nationalite', models.CharField(max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.categorie_employer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.service')),
            ],
        ),
        migrations.AlterField(
            model_name='detteemploye',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employer'),
        ),
        migrations.AlterField(
            model_name='remuneration',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employer'),
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
