# Generated by Django 5.1.1 on 2024-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0012_categorie_employer_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='mail',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='adresse',
            field=models.TextField(max_length=30),
        ),
    ]
