# Generated by Django 5.1.1 on 2024-09-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0013_employer_mail_alter_employer_adresse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie_employer',
            new_name='Categorie_employe',
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=20)),
                ('postnom', models.TextField(max_length=20)),
                ('sexe', models.TextField(max_length=2)),
                ('etat_civil', models.TextField(max_length=5)),
                ('nb_enfant', models.IntegerField()),
                ('date_naiss', models.DateField()),
                ('date_engage', models.DateField()),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.TextField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('niveau_etu', models.CharField(max_length=30)),
                ('fonction', models.CharField(max_length=30)),
                ('nationalite', models.CharField(max_length=20)),
                ('dossier', models.FileField(upload_to='dossiers_agents/')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.categorie_employe')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.service')),
            ],
        ),
        migrations.AlterField(
            model_name='detteemploye',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employe'),
        ),
        migrations.AlterField(
            model_name='remuneration',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riviapp.employe'),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
