# Generated by Django 5.1.1 on 2024-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0014_rename_categorie_employer_categorie_employe_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie_employe',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
