# Generated by Django 5.1.1 on 2024-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0015_alter_categorie_employe_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuneration',
            name='periode',
        ),
        migrations.AddField(
            model_name='remuneration',
            name='annee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='mois',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Periode',
        ),
    ]
