# Generated by Django 5.1.1 on 2024-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0016_remove_remuneration_periode_remuneration_annee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remuneration',
            old_name='inpp',
            new_name='allocation_fam',
        ),
        migrations.RenameField(
            model_name='remuneration',
            old_name='onem',
            new_name='communication',
        ),
        migrations.AddField(
            model_name='remuneration',
            name='heure_supp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='joursmaladie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='logement',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='prime',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='sal_anciennete',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='sal_heure_supp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='sal_jrs_maladie',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='transport',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
