# Generated by Django 5.1.1 on 2024-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0017_rename_inpp_remuneration_allocation_fam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detteemploye',
            name='avance_sur_salaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detteemploye',
            name='periodes_couverture',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detteemploye',
            name='pret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detteemploye',
            name='reste',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='touche',
            field=models.BooleanField(default=False),
        ),
    ]
