# Generated by Django 5.1.1 on 2024-09-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0018_detteemploye_avance_sur_salaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneration',
            name='inpp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='onem',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remuneration',
            name='pret',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
