# Generated by Django 5.1.1 on 2024-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0019_remuneration_inpp_remuneration_onem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneration',
            name='id_dette_employe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
