# Generated by Django 5.1.1 on 2024-09-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0020_remuneration_id_dette_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remuneration',
            name='id_dette_employe',
        ),
    ]
