# Generated by Django 5.1.1 on 2024-09-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0021_remove_remuneration_id_dette_employe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remuneration',
            old_name='touche',
            new_name='paid',
        ),
    ]
