# Generated by Django 5.1.1 on 2024-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0022_rename_touche_remuneration_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='remuneration',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
    ]
