# Generated by Django 5.1.1 on 2024-10-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0023_remuneration_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='is_occupied',
            field=models.BooleanField(default=0),
        ),
    ]
