# Generated by Django 5.1.1 on 2024-10-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0024_salle_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='is_booked',
            field=models.BooleanField(default=0),
        ),
    ]
