# Generated by Django 5.1.1 on 2024-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0025_salle_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='is_blocked',
            field=models.BooleanField(default=0),
        ),
    ]
