# Generated by Django 5.1.1 on 2024-10-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0026_salle_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='is_blocked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='boutique',
            name='is_occupied',
            field=models.BooleanField(default=0),
        ),
    ]
