# Generated by Django 5.1.1 on 2024-10-18 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0027_boutique_is_blocked_boutique_is_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationsalle',
            name='client',
        ),
        migrations.AddField(
            model_name='reservationsalle',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.entreprise'),
        ),
        migrations.AddField(
            model_name='reservationsalle',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='riviapp.enregistrer'),
        ),
        migrations.AlterField(
            model_name='reservationsalle',
            name='etatrsv',
            field=models.IntegerField(default=2),
        ),
    ]
