# Generated by Django 5.1.1 on 2024-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0028_remove_reservationsalle_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affectation', models.CharField(choices=[('REC', 'Réception'), ('PDV', 'Point de Vente'), ('FIN', 'Finance et Comptabilité'), ('MAG', 'Magasin et Stock'), ('HKP', 'House Keeping'), ('GAR', 'Garde et Sécurité'), ('RHM', 'Ressources Humaines'), ('INF', 'Informatique'), ('CUI', 'Cuisine'), ('GER', 'Gérance')], max_length=30)),
                ('is_avalable', models.BooleanField(default=True)),
            ],
        ),
    ]
