# Generated by Django 5.1.1 on 2024-10-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0029_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='affectation',
            field=models.CharField(choices=[('REC', 'Réception'), ('PDV', 'Point de Vente'), ('FIN', 'Finance et Comptabilité'), ('MAG', 'Magasin et Stock'), ('HKP', 'House Keeping'), ('GAR', 'Garde et Sécurité'), ('RHM', 'Ressources Humaines'), ('INF', 'Informatique'), ('CUI', 'Cuisine'), ('GER', 'Gérance')], max_length=30, unique=True),
        ),
    ]
