# Generated by Django 5.1.1 on 2024-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0030_alter_modules_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='affectation',
            field=models.CharField(choices=[('REC', 'Réception'), ('PDV', 'Point de Vente'), ('FIN', 'Finance et Comptabilité'), ('MAG', 'Magasin et Stock'), ('HKP', 'House Keeping'), ('RHM', 'Ressources Humaines')], max_length=30, unique=True),
        ),
    ]
