# Generated by Django 5.1.1 on 2024-10-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0031_alter_modules_affectation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
