# Generated by Django 5.1.1 on 2024-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0032_rename_modules_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandevente',
            name='datev',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='affectation',
            field=models.CharField(choices=[('REC', 'Réception'), ('PDV', 'Point de Vente'), ('FIN', 'Finance et Comptabilité'), ('MAG', 'Magasin et Stock'), ('HKP', 'House Keeping'), ('RHM', 'Ressources Humaines'), ('IAT', 'Intellicence Articficielle')], max_length=30, unique=True),
        ),
    ]
