# Generated by Django 5.1.1 on 2024-10-20 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0033_alter_commandevente_datev_alter_module_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementfacture',
            name='utilisateur',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
