# Generated by Django 5.1.1 on 2024-10-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviapp', '0034_paiementfacture_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurestau',
            name='prix',
            field=models.FloatField(),
        ),
    ]
